name       : libxml++26
version    : 2.42.2
release    : 2
source     :
    - https://download.gnome.org/sources/libxml++/2.42/libxml++-2.42.2.tar.xz : a433987f54cc1ecaa84af26af047a62df9e884574e0d686e5ddc6f70441c152b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ bindings to libxml2
description: |
    C++ bindings to libxml2
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libxml-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
